[project]
name = "local-multimodal-personal-knowledge-base"
version = "0.1.0"
description = "A localized personal knowledge based on multimodal RAG."
authors = [
    {name = "emrekuruu",email = "emre.kuru@ozu.edu.tr"}
]
readme = "README.md"
requires-python = ">=3.11,<3.14"
dependencies = [
    "torch",
    "python-dotenv",
    "typer",
    "pillow",
    "langchain",
    "langchain-ollama",
    "langchain-chroma",
    "chromadb",
    "pymupdf",
    "voyageai (>=0.3.7,<0.4.0)",
    "langchain-openai (>=1.1.10,<2.0.0)",
    "tavily-python",
]

[project.scripts]
lmpkb = "lmpkb.cli:app"


[tool.poetry]
packages = [{include = "lmpkb"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
