[project]
name = "local-multimodal-personal-knowledge-base"
version = "0.1.0"
description = "A localized personal knowledge based on multimodal RAG."
authors = [
    {name = "emrekuruu",email = "emre.kuru@ozu.edu.tr"}
]
readme = "README.md"
requires-python = ">=3.11,<3.15"
dependencies = [
    "ollama (>=0.6.1,<0.7.0)",
    "torch (>=2.10.0,<3.0.0)",
    "colpali-engine (>=0.3.14,<0.4.0)",
    "python-dotenv (>=1.2.1,<2.0.0)",
    "typer (>=0.15.0,<0.16.0)"
]

[project.scripts]
lmpkb = "lmpkb.cli:app"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
